🔥 Remove .github as ignored path
stone-payments/sre-platform-template-setup pull request #4
Opened 2022-10-19 18:09 UTC by Giomaster

Signed-off-by: Giomaster <giomaster127@gmail.com>

2022-10-19 21:04 UTC, dgmorales reviewed
Acho que o @Feggah devia dar o review aqui, pois ele conhece bem mais este script.

No geral, me parece que atuar no .github pode ser útil em outros casos eventualmente, como templates de PR e issues, por exemplo.

2022-10-19 21:07 UTC, Feggah commented
Como que foi testado esse PR e o que ele tá tentando resolver? Olhando a modificação parece ok, queria entender pq precisa incluir o folder pra ser modificado pelo repo-setup

2022-10-27 16:37 UTC, Feggah requested changes

2022-10-27 16:37 UTC, Feggah commented on setup.py
> -
Não remove essa linha, é padrão do style guide do Python (PEP8) ter duas linhas brancas entre funções. Se quiser dar uma olhada na referência: https://peps.python.org/pep-0008/#blank-lines

2022-10-31 19:22 UTC, Feggah commented on setup.py
> +    rename_folders(ROOT)
Como você tirou o argumento da função, precisa tirar o argumento na hora de invocar

```suggestion
    rename_folders()
```

2022-11-01 19:12 UTC, Feggah requested changes
Testei o workflow aqui e não funcionou.

O `.git` no IGNORE_FOLDERS não está funcionando corretamente, dá uma olhada: https://github.com/platform-test-org/test-review-2/actions/runs/3372134809/jobs/5595203264

Ele tentou fazer replace de um arquivo dentro da pasta `.git`

2022-11-03 17:01 UTC, merged