✅ Add unit tests and cleaning code
stone-payments/sre-platform-template-setup pull request #5
Opened 2022-10-27 21:29 UTC by Giomaster

2022-11-03 17:40 UTC, Feggah reviewed
Eu acho que não faz muito sentido ter que transformar todo o script em classes para que os testes funcionem. As classes acabam sendo apenas um mecanismo para funcionar os testes e a própria existência delas não faz muito sentido (IMO).

O que você acha de manter o código do script inalterado (apenas correção de linting caso precise) e fazer os testes unitários para cada função?

Quando estávamos desenvolvendo a API [infra-modernization](https://github.com/stone-payments/infra-modernization), utilizamos o framework [pytest](https://docs.pytest.org/en/7.2.x/getting-started.html) e pelo primeiro exemplo da documentação dele, é basicamente o que precisamos: testar cada função isoladamente, sem necessidade de criar diversas classes, keeping it simple

2022-11-10 13:16 UTC, cnatan commented
É louvável a iniciativa de refatorar o código para melhorar legibilidade e adicionar cobertura de testes, e automatizar sua execução.

Trago algumas ressalvas em relação à adoção abrangente de classes para esse script, se tratando de python e sendo um script simples e curto, acho que a complexidade adicionada introduzindo as classes não se paga em questão de legibilidade, “testabilidade”, ou manutenibilidade. Já que o script já cumpre um função mínima de fácil compreensão, e as classes também não são requisitos necessários para introduzir os testes, como o teste não exige nenhuma complexidade de mocks ou injeção de dependências que geralmente são facilitadas por OOP.

Acho justo de toda forma manter os testes, porém testando diretamente as funções soltas no pacote, vejo que assim manteremos uma melhor facilidade de manutenção, e agregaremos mais qualidade e segurança contra introdução de bugs graças aos testes.
Os docstrings e linting também são ótimas adições.

2022-11-11 17:14 UTC, Feggah requested changes
Alguns pontos individuais no código comentados abaixo.

De forma mais geral:
- Acredito que seria bom adicionar o teste pra função `main`, que é a principal orquestradora do setup
- Ao invés de criar um Dockerfile e os arquivos serem mudados conforme os testes rodam -- fazendo com que seja importante pensar em quais arquivos existem, se já foram ou não modificados, etc -- o que acha de mockar a lib `os`?

2022-11-11 17:14 UTC, Feggah commented on setup.py
> +    replace_folder_name(replace_dict, ROOT, IGNORE_FOLDERS)
Esse `replace_dict` não está mais sendo uma variável global, porque está dentro do escopo do `if __name__ == "__main__"`, certo? Além disso, a função main não recebe ela por parâmetro.

Como que essa variável está sendo populada pra função main?

2022-11-11 17:14 UTC, Feggah commented on test.py
> +    """
```suggestion
  def test_has_not_any_item_in_string(self):
    """
    Hasn't any item in string and should return false
    """
```

2022-11-14 19:26 UTC, Giomaster commented on setup.py
> +    ".github",
Opa! Não é mais necessário dar replace nos workflows do github.

2022-11-14 19:31 UTC, Giomaster commented on setup.py
> +    with open(file_path,'r',errors='surrogateescape', encoding="utf-8") as file:
Nenhum erro é gerado se não especificar um `encoding`. Foi meramente por questões de lint.

2022-11-14 19:42 UTC, Giomaster commented on setup.py
> +    replace_folder_name(replace_dict, ROOT, IGNORE_FOLDERS)
Na verdade `replace_dict` continua sendo uma variavel global porque declarar uma variavel dentro de uma condicional como o _if_ por exemplo não o torna de uso exclusivo do mesmo. Seria diferente o caso se declarasse tal variavel em uma função.

2022-11-14 19:53 UTC, Giomaster commented
Concordo que se tivesse uma unit-test para a `main` seria de fato um bom teste para garantir que o proposito desse script estaria sendo respeitada e por isso vou estar pensando em uma maneira satisfatório de estar inserindo um case para a main.

2022-11-23 18:31 UTC, Feggah approved these changes
LGTM 🚀

2022-11-23 18:50 UTC, merged